routes/web.php
<?php

use App\Order;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['verify'=>true]);
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('auth.index');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('auth.callback');

Route::get('/', 'HomeController@index')->name('landing-page');
Route::get('services/search', 'HomeController@searchAgentJob')->name('service.search');
Route::get('services', 'HomeController@services')->name('services');
Route::get('service/show/{id}', 'HomeController@showService')->name('service.show');
Route::get('service/show/{id}/filter', 'HomeController@filterService')->name('service.filter-service');

Route::post('order/package/{id}', 'HomeController@makeOrder')->name('order.store')->middleware('auth');
Route::post('order/package/{id}/payment', 'PaymentController@orderPayment')->name('order.payment');
Route::get('order/package/{id}', 'HomeController@redirectOrderPage');
Route::post('payment/notification', 'PaymentController@notification');
Route::get('promo/check', 'HomeController@checkPromoCode')->name('promo.check');
Route::get('contact-us', 'ContactController@index')->name('contact-us.index');
Route::get('faq', 'HomeController@faq')->name('faq.index');
Route::get('faq/search', 'Admin\FaqController@seach')->name('faq.search');
Route::get('testimony', 'HomeController@testimonies')->name('testimony');
Route::get('blog/search', 'BlogController@search')->name('blog.search');
Route::resource('blog', 'BlogController')->only(['index', 'show']);
Route::get('search/agentjob', 'HomeController@searchAgentJob')->name('agentjob.search');
Route::get('blog/categories/{id}', 'BlogCategoryController@show')->name('blog-category.show');
Route::name('message.')->prefix('message')->middleware('exceptAdmin')->group(function () {
    Route::get('/', 'MessageController@index')->name('index');
    Route::get('fetch/{session_id}', 'MessageController@fetch')->name('fetch');
    Route::post('send/{session_id}', 'MessageController@send')->name('send');
});
Route::post('contact-us', 'ContactController@send')->name('contact-us.store');
Route::get('payment/redirect', 'PaymentController@redirect')->name('payment.redirect');

Route::namespace('Admin')->middleware('admin')->prefix('admin')->group(function () {
    Route::get('dashboard', 'AdminController@index')->name('admin.dashboard');
    Route::get('setting', 'AdminController@setting')->name('admin.setting');
    Route::put('token-conversion', 'AdminController@updateToken')->name('admin.convert-token');
    Route::prefix('manage')->name('manage.')->group(function(){
        Route::get('/', 'HomeController@index');
        Route::get('agent/search', 'AgentController@search')->name('agent.search');
        Route::resource('user', 'UserController');
        Route::resource('agent', 'AgentController');
        Route::resource('admin', 'AdminController')->except('index');
        Route::post('faq-category/store', 'FaqController@storeCategory')->name('faq.store-category');
        Route::get('faq-category/destroy/{id}', 'FaqController@destroyCategory')->name('faq.destroy-category');
        Route::resource('faq', 'FaqController')->except(['show']);
        Route::resource('blog', 'BlogController');
        Route::resource('blog-category', 'BlogCategoryController')->only(['store', 'update', 'destroy']);
        Route::resource('service', 'ServiceController')->except(['create']);
        Route::resource('service-category', 'ServiceCategoryController')->except(['create', 'show', 'edit']);
        Route::get('contact-us/search', 'ContactController@search')->name('contact-us.search');
        Route::resource('contact-us', 'ContactController')->except(['create', 'store', 'show']);
        Route::resource('testimony', 'TestimonyController')->only(['index', 'update', 'destroy']);
        Route::resource('promo', 'PromoController')->except(['create', 'show', 'edit']);
        Route::resource('subscription', 'SubscriptionController');
        Route::resource('reason', 'ReasonController')->except(['show']);
        Route::get('package/{id}', 'PackageController@index')->name('package.index');
        Route::resource('package', 'PackageController')->except(['index']);
        Route::get('service-extras/{id}', 'ServiceExtrasController@index')->name('service-extras.index');
        Route::resource('service-extras', 'ServiceExtrasController')->except(['index']);
    });
});

Route::get('download/order/{id}/result/{result_id}', 'DownloadController@downloadResult')->name('order.result.download');

Route::name('user.')->prefix('user')->middleware(['auth', 'verified'])->group(function () {
    Route::resource('subscription', 'SubscriptionController')->only(['index', 'show']);
    Route::post('subscription/show/{id}/payment', 'PaymentController@subscriptionPayment')->name('subscription.payment');
    Route::get('order/{id}/chat', 'MessageController@chat')->name('chat.index');
    Route::get('order/{id}/get-chat', 'MessageController@getChat')->name('chat.get');
    Route::post('order/chat', 'MessageController@sendChat')->name('chat.store');
    Route::prefix('profile')->group(function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::get('edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('edit', 'ProfileController@update')->name('profile.update');
        Route::put('edit/avatar', 'ProfileController@avatarUpdate')->name('profile.avatar.update');
    });
    Route::namespace('User')->group(function() {
        Route::post('order/{id}/review', 'OrderController@sendReview')->name('order.review');
        Route::get('dashboard', 'HomeController@index')->name('dashboard');
        Route::resource('order', 'OrderController');
        Route::get('order/{id}/result/accept/{result_id}', 'OrderController@acceptResult')->name('order.accept');
        Route::get('order/{id}/result/reject/{result_id}', 'OrderController@rejectResult')->name('order.reject');
        Route::resource('job', 'JobController');
        Route::resource('testimony', 'TestimonyController')->only(['index', 'create', 'store']);
        Route::resource('transaction', 'TransactionController');
    });
});

Route::prefix('agent')->name('agent.')->middleware(['agent', 'verified'])->group(function () {
    Route::get('order/{id}/chat', 'MessageController@chat')->name('chat.index');
    Route::post('order/chat', 'MessageController@sendChat')->name('chat.store');
    Route::get('order/{id}/get-chat', 'MessageController@getChat')->name('chat.get');
    Route::prefix('profile')->group(function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::put('edit', 'ProfileController@update')->name('profile.update');
        Route::put('edit/avatar', 'ProfileController@avatarUpdate')->name('profile.avatar.update');
    });
    Route::namespace('Agent')->group(function () {
        Route::get('bid-history', 'OrderController@bidHistory')->name('bid-history');
        Route::redirect('/', 'dashboard');
        Route::get('dashboard', 'HomeController@index')->name('dashboard');
        Route::get('testimony', 'TestimonyController@index')->name('testimony.index');
        Route::get('testimony/{service_id}', 'TestimonyController@show')->name('testimony.show');
        Route::get('service/see-extras/{id}', 'ServiceController@seeExtras')->name('service.extras');
        Route::resource('service', 'ServiceController');
        Route::get('service/manage-package/{id}', 'ServiceController@managePackage')->name('service.package');
        Route::get('list-request/complaint', 'OrderController@complaint')->name('list-request.complaint');
        Route::get('list-request/history', 'OrderController@history')->name('list-request.history');
        Route::get('list-request/incoming', 'OrderController@incoming')->name('list-request.incoming');
        Route::put('list-request/approval/{id}', 'OrderController@approval')->name('list-request.approval');
        Route::put('list-request/progress/{id}', 'OrderController@progressUpdate')->name('list-request.progress');
        Route::delete('list-request/delete/{id}', 'OrderController@destroy');
        Route::post('list-request/send-review/{id}', 'OrderController@sendReview')->name('list-request.send-review');
        Route::post('list-request/send-result/{id}', 'OrderController@sendResult')->name('list-request.send-result');
        Route::post('list-request/send-revision/{id}', 'OrderController@sendRevision')->name('list-request.send-revision');
        Route::get('list-request/search', 'OrderController@search')->name('list-request.search');
        Route::resource('list-request', 'OrderController');
        Route::resource('portfolio', 'PortfolioController');
    });
});

app/ContactUs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ContactUs extends Model
{
    protected $fillable = ['name', 'email', 'message', 'answer', 'is_answered'];
}

resources/views/contact-us/read.blade.php
@extends('layouts.admin-master')
@section('page-id', 'readMessage')
@section('page-name', 'Message From Customer')
@section('page-title', 'Message From Customer')
@section('header')
    <header>
        @if(session('success'))
            <div class="alert alert-default" role="alert">
                {{ session('success') }}
            </div>
        @endif
        <div class="alert alert-default" role="alert" style="display: none">
            Successfully reply message from customer
        </div>
        <div class="row mb-5 justify-content-between">
            <div class="col-12">
                <form class="navbar-search d-block navbar-search-light mr-sm-3 transform-none"
                action="{{ route('manage.contact-us.search') }}" id="navbar-search-main" method="get">
                    <div class="form-group mb-0">
                        <div class="input-group input-group-alternative input-group-merge">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="search-message">
                                    <i class="fas fa-search"></i>
                                </label>
                            </div>
                            <input class="form-control" type="text" id="search-message"
                            value="{{ $searching ?? '' }}" name="search" placeholder="Search by email or name sender" required>
                        </div>
                    </div>
                    <button type="button" class="close" data-action="search-close"
                            data-target="#navbar-search-main" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <a href="{{ route('manage.contact-us.index') }}">
                    <div class="card card-stats">
                        <div class="card-body">
                            <div class="row">
                                <div class="col d-flex flex-column">
                                    <h5 class="card-title text-uppercase text-link mb-0">Unanswered message</h5>
                                    <span class="h2 font-weight-bold mb-0">{{ $totalNotAnswered }}</span>
                                </div>
                                <div class="col-auto">
                                    <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                                        <i class="fas fa-envelope"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6">
                <a href="{{ route('manage.contact-us.search') . '?search=is_answered=true' }}">
                    <div class="card card-stats">
                        <div class="card-body">
                            <div class="row">
                                <div class="col d-flex flex-column">
                                    <h5 class="card-title text-uppercase text-link mb-0">Answered message</h5>
                                    <span class="h2 font-weight-bold mb-0">{{ $totalAnswered }}</span>
                                </div>
                                <div class="col-auto">
                                    <div class="icon icon-shape bg-gradient-success text-white rounded-circle shadow">
                                        <i class="far fa-envelope-open"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </header>
@endsection
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header border-0 pb-0">
                    <h3 class="mb-0">Unanswered</h3>
                </div>
                <div class="card-body">
                    <div class="accordion" id="accordionJobHistory">
                        @forelse ($messages as $message)
                            <article class="accordion__item">
                                <div id="heading{{ $message->id }}" class="d-flex mb-2 align-items-center">
                                    <h2 class="mb-0 mr-auto job-history-title">
                                        <button class="btn p-0 shadow-none btn-link collapsed" type="button"
                                        data-toggle="collapse" aria-expanded="false"
                                        data-target="#collapse{{ $loop->index }}"
                                        aria-controls="collapse{{ $loop->index }}">
                                            <i class="fas fa-chevron-up rotate-180 mr-2"></i>
                                            {{ 'Delivered at : ' . $message->created_at->format('d M Y') }}
                                        </button>
                                    </h2>
                                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                                    data-target="#delete-message-customer" data-id="{{ $message->id }}"
                                    data-sender="{{ $message->email }}">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </div>

                                <div id="collapse{{ $loop->index }}" aria-labelledby="heading{{ $loop->index }}"
                                     class="collapse" data-parent="#accordionJobHistory">
                                    <div class="card-body">
                                        {{ $message->message }}
                                        <form action="{{ route('manage.contact-us.update', $message->id) }}"
                                              class="mt-3 border-top pt-4" method="post">
                                            @csrf @method('PUT')
                                            <div class="form-group">
                                                <label for="message-review" class="text-gray">
                                                    Reply to their email
                                                </label>
                                                <textarea name="answer" class="form-control" id="message-review"
                                                placeholder="Oooh thanks for your advice, we will ..."
                                                rows="10" {{ $message->is_answered == true ? 'readonly' : '' }}
                                                required></textarea>
                                            </div>
                                            <button type="submit" class="btn btn-default">Send Review</button>
                                            <span class="text-info d-none is-answered">
                                                You answer this on {{ $message->updated_at->format('d M Y H:i') }}
                                            </span>
                                        </form>
                                    </div>
                                    <div class="card-footer border-top-0 d-flex justify-between text-default">
                                        <p>
                                            From:
                                            <span class="font-weight-600">
                                            {{ $message->email . ' (' . $message->name . ')' }}
                                        </span>
                                        </p>
                                    </div>
                                </div>
                            </article>
                        @empty
                            @if (Route::currentRouteName() === 'manage.contact-us.index')
                                <img src="{{ asset('img/empty-state.svg') }}" alt="No history job" height="230"
                                     class="mx-auto d-block">
                                <h1 class="text-center h2 mt-5 text-muted">
                                    Yeayy you have unanswered message from customer!
                                    <a href="{{ route('manage.contact-us.index') }}" class="text-link d-block">
                                        Refresh <i class="fas fa-sync"></i>
                                    </a>
                                </h1>
                            @else
                                <img src="{{ asset('img/not-found.jpg') }}" alt="No message found" height="230"
                                     class="mx-auto d-block">
                                <h1 class="text-center h2 mt-5 text-muted">
                                    Message not found / you type a wrong format
                                    <a href="{{ route('manage.contact-us.index') }}" class="text-link d-block mt-2">
                                        Back to prev <i class="fas fa-undo-alt ml-1"></i>
                                    </a>
                                </h1>
                            @endif
                        @endforelse
                    </div>
                </div>
                <div class="card-footer border-top-0 py-0">
                    {{ $messages->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('element')
    <div class="modal fade" id="delete-message-customer" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete customer message</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        Are you sure wanna remove message from
                        <span class="modal-message-sender font-weight-bold"></span>
                    </p>
                    <form action="{{--routing on js--}}" method="post" id="form-delete-message-customer">
                        @csrf @method('DELETE')
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger" form="form-delete-message-customer">
                        Yes, delete it
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalLoader" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="loader loader--style3" title="2">
                        <img src="{{ asset('img/loader.svg') }}" alt="Loader">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contact-us/send.blade.php
@extends('layouts.customer-master')
@section('page-title', 'Contact us')
@section('page-id', 'contactUs')
@section('header')
    @include('partials.nav')
@endsection
@section('content')
    <div class="container">
        @if (session('success'))
            <div class="alert alert--success mb-5">
                {{ session('success') }}
            </div>
        @endif
        <div class="row justify-content-between contact-us">
            <section class="contact-us__illustration col-12 col-lg-6 col-xl-5">
                <img src="{{ asset('img/contact-us.jpg') }}" class="contact-us__img" alt="Contact us Desainin"
                     draggable="false">
            </section>
            <section class="contact-us__message col-12 col-lg-6">
                <h1 class="contact-us__heading">Have any idea? <br> We glad to hear that</h1>
                <form class="contact-us__form" action="{{ route('contact-us.store' )}}" method="post">
                    @csrf
                    <input type="text" class="contact-us__input" name="name" placeholder="What's your name"
                           autocomplete="name" required autofocus>
                    <input type="email" class="contact-us__input" name="email" placeholder="What's your email"
                           autocomplete="email" required>
                    <textarea name="message" class="contact-us__input" rows="15" placeholder="Message..."></textarea>
                    <button type="submit" class="contact-us__submit-btn">Send your message</button>
                </form>
            </section>
        </div>
    </div>
@endsection