routes/web.php
<?php

use App\Order;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['verify'=>true]);
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('auth.index');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('auth.callback');

Route::get('/', 'HomeController@index')->name('landing-page');
Route::get('services/search', 'HomeController@searchAgentJob')->name('service.search');
Route::get('services', 'HomeController@services')->name('services');
Route::get('service/show/{id}', 'HomeController@showService')->name('service.show');
Route::get('service/show/{id}/filter', 'HomeController@filterService')->name('service.filter-service');

Route::post('order/package/{id}', 'HomeController@makeOrder')->name('order.store')->middleware('auth');
Route::post('order/package/{id}/payment', 'PaymentController@orderPayment')->name('order.payment');
Route::get('order/package/{id}', 'HomeController@redirectOrderPage');
Route::post('payment/notification', 'PaymentController@notification');
Route::get('promo/check', 'HomeController@checkPromoCode')->name('promo.check');
Route::get('contact-us', 'ContactController@index')->name('contact-us.index');
Route::get('faq', 'HomeController@faq')->name('faq.index');
Route::get('faq/search', 'Admin\FaqController@seach')->name('faq.search');
Route::get('testimony', 'HomeController@testimonies')->name('testimony');
Route::get('blog/search', 'BlogController@search')->name('blog.search');
Route::resource('blog', 'BlogController')->only(['index', 'show']);
Route::get('search/agentjob', 'HomeController@searchAgentJob')->name('agentjob.search');
Route::get('blog/categories/{id}', 'BlogCategoryController@show')->name('blog-category.show');
Route::name('message.')->prefix('message')->middleware('exceptAdmin')->group(function () {
    Route::get('/', 'MessageController@index')->name('index');
    Route::get('fetch/{session_id}', 'MessageController@fetch')->name('fetch');
    Route::post('send/{session_id}', 'MessageController@send')->name('send');
});
Route::post('contact-us', 'ContactController@send')->name('contact-us.store');
Route::get('payment/redirect', 'PaymentController@redirect')->name('payment.redirect');

Route::namespace('Admin')->middleware('admin')->prefix('admin')->group(function () {
    Route::get('dashboard', 'AdminController@index')->name('admin.dashboard');
    Route::get('setting', 'AdminController@setting')->name('admin.setting');
    Route::put('token-conversion', 'AdminController@updateToken')->name('admin.convert-token');
    Route::prefix('manage')->name('manage.')->group(function(){
        Route::get('/', 'HomeController@index');
        Route::get('agent/search', 'AgentController@search')->name('agent.search');
        Route::resource('user', 'UserController');
        Route::resource('agent', 'AgentController');
        Route::resource('admin', 'AdminController')->except('index');
        Route::post('faq-category/store', 'FaqController@storeCategory')->name('faq.store-category');
        Route::get('faq-category/destroy/{id}', 'FaqController@destroyCategory')->name('faq.destroy-category');
        Route::resource('faq', 'FaqController')->except(['show']);
        Route::resource('blog', 'BlogController');
        Route::resource('blog-category', 'BlogCategoryController')->only(['store', 'update', 'destroy']);
        Route::resource('service', 'ServiceController')->except(['create']);
        Route::resource('service-category', 'ServiceCategoryController')->except(['create', 'show', 'edit']);
        Route::get('contact-us/search', 'ContactController@search')->name('contact-us.search');
        Route::resource('contact-us', 'ContactController')->except(['create', 'store', 'show']);
        Route::resource('testimony', 'TestimonyController')->only(['index', 'update', 'destroy']);
        Route::resource('promo', 'PromoController')->except(['create', 'show', 'edit']);
        Route::resource('subscription', 'SubscriptionController');
        Route::resource('reason', 'ReasonController')->except(['show']);
        Route::get('package/{id}', 'PackageController@index')->name('package.index');
        Route::resource('package', 'PackageController')->except(['index']);
        Route::get('service-extras/{id}', 'ServiceExtrasController@index')->name('service-extras.index');
        Route::resource('service-extras', 'ServiceExtrasController')->except(['index']);
    });
});

Route::get('download/order/{id}/result/{result_id}', 'DownloadController@downloadResult')->name('order.result.download');

Route::name('user.')->prefix('user')->middleware(['auth', 'verified'])->group(function () {
    Route::resource('subscription', 'SubscriptionController')->only(['index', 'show']);
    Route::post('subscription/show/{id}/payment', 'PaymentController@subscriptionPayment')->name('subscription.payment');
    Route::get('order/{id}/chat', 'MessageController@chat')->name('chat.index');
    Route::get('order/{id}/get-chat', 'MessageController@getChat')->name('chat.get');
    Route::post('order/chat', 'MessageController@sendChat')->name('chat.store');
    Route::prefix('profile')->group(function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::get('edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('edit', 'ProfileController@update')->name('profile.update');
        Route::put('edit/avatar', 'ProfileController@avatarUpdate')->name('profile.avatar.update');
    });
    Route::namespace('User')->group(function() {
        Route::post('order/{id}/review', 'OrderController@sendReview')->name('order.review');
        Route::get('dashboard', 'HomeController@index')->name('dashboard');
        Route::resource('order', 'OrderController');
        Route::get('order/{id}/result/accept/{result_id}', 'OrderController@acceptResult')->name('order.accept');
        Route::get('order/{id}/result/reject/{result_id}', 'OrderController@rejectResult')->name('order.reject');
        Route::resource('job', 'JobController');
        Route::resource('testimony', 'TestimonyController')->only(['index', 'create', 'store']);
        Route::resource('transaction', 'TransactionController');
    });
});

Route::prefix('agent')->name('agent.')->middleware(['agent', 'verified'])->group(function () {
    Route::get('order/{id}/chat', 'MessageController@chat')->name('chat.index');
    Route::post('order/chat', 'MessageController@sendChat')->name('chat.store');
    Route::get('order/{id}/get-chat', 'MessageController@getChat')->name('chat.get');
    Route::prefix('profile')->group(function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::put('edit', 'ProfileController@update')->name('profile.update');
        Route::put('edit/avatar', 'ProfileController@avatarUpdate')->name('profile.avatar.update');
    });
    Route::namespace('Agent')->group(function () {
        Route::get('bid-history', 'OrderController@bidHistory')->name('bid-history');
        Route::redirect('/', 'dashboard');
        Route::get('dashboard', 'HomeController@index')->name('dashboard');
        Route::get('testimony', 'TestimonyController@index')->name('testimony.index');
        Route::get('testimony/{service_id}', 'TestimonyController@show')->name('testimony.show');
        Route::get('service/see-extras/{id}', 'ServiceController@seeExtras')->name('service.extras');
        Route::resource('service', 'ServiceController');
        Route::get('service/manage-package/{id}', 'ServiceController@managePackage')->name('service.package');
        Route::get('list-request/complaint', 'OrderController@complaint')->name('list-request.complaint');
        Route::get('list-request/history', 'OrderController@history')->name('list-request.history');
        Route::get('list-request/incoming', 'OrderController@incoming')->name('list-request.incoming');
        Route::put('list-request/approval/{id}', 'OrderController@approval')->name('list-request.approval');
        Route::put('list-request/progress/{id}', 'OrderController@progressUpdate')->name('list-request.progress');
        Route::delete('list-request/delete/{id}', 'OrderController@destroy');
        Route::post('list-request/send-review/{id}', 'OrderController@sendReview')->name('list-request.send-review');
        Route::post('list-request/send-result/{id}', 'OrderController@sendResult')->name('list-request.send-result');
        Route::post('list-request/send-revision/{id}', 'OrderController@sendRevision')->name('list-request.send-revision');
        Route::get('list-request/search', 'OrderController@search')->name('list-request.search');
        Route::resource('list-request', 'OrderController');
        Route::resource('portfolio', 'PortfolioController');
    });
});

app/Http/Controllers/Admin/AgentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\File;

class AgentController extends Controller
{

    public function index()
    {
        $listBank = json_decode(File::get('js/bank_indonesia.json'));
        $agents = User::where('role', 'agent')->paginate(10);
        return view('agent.manage', ['agents' => $agents, 'listBank' => $listBank]);
    }

    public function create()
    {
        return view('agent.register');
    }

    public function store(Request $request)
    {
        $request->validate([
            'agent_name' => 'required|string',
            'email' => 'required|email:rfc',
            'agent_password' => 'required|min:8|max:20',
            'agent_phone' => 'required',
            'agent_address' => 'required|min:10',
            'name_card' => 'nullable|mimes:doc,docx,pdf',
            'bank' => 'required|integer',
            'agent_account' => 'required|integer'
        ]);
        $agent = User::create([
            'name' => $request->agent_name,
            'email' => $request->agent_email,
            'password' => Hash::make($request->agent_password),
            'username' => Str::snake($request->agent_name),
            'role' => 'agent',
        ]);
        $agent->profile()->create([
            'avatar' => 'files/people.webp',
            'handphone' => $request->agent_phone,
            'address' => $request->agent_address,
            'name_card' => $request->file('name_card')->store('public/files') ?? '',
            'bank' => $request->bank,
            'account_number' => $request->agent_account,
        ]);
        return redirect()->back()->with('success', 'Agent Account Created Successfully');
    }

    public function show($id)
    {
        $agent = User::where('role', 'agent')->findOrFail($id);
        return view('agent.show', ['agent', $agent]);
    }

    public function edit($id)
    {
        $agent = User::where('role', 'agent')->findOrFail($id);
        return view('agent.edit', ['agent', $agent]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'agent_name' => 'required|string',
            'agent_email' => 'required|email:rfc',
            'agent_password' => 'required|min:8|max:20',
            'agent_phone' => 'required',
            'agent_address' => 'required|min:10',
            'name_card' => 'nullable|mimes:doc,docx,pdf',
            'bank' => 'required',
            'agent_account' => 'required|integer'
        ]);
        $agent = User::findOrFail($id);
        $agent->email = $request->agent_email;
        $agent->name = $request->agent_name;
        $agent->profile->handphone = $request->agent_phone;
        $agent->profile->bank = $request->bank;
        $agent->profile->account_number = $request->agent_account;
        $agent->profile->address = $request->agent_address;
        if ($request->hasFile('name_card')) {
            $agent->profile->name_card = $request->file('name_card')->store('public/files');
        }
        $agent->profile->save();
        $agent->save();
        return redirect()->back()->with('success', 'Agent Account Updated Successfully');
    }

    public function destroy($id)
    {
        $agent = User::where('role', 'agent')->findOrFail($id);
        $profile = $agent->profile;
        $portfolios = $profile->portfolio;
        if ($portfolios->count() != 0) {
            foreach ($portfolios as $portfolio) {
                Storage::delete($portfolio->image_url);
                $portfolio->delete();
            }
        }
        Storage::delete($profile->avatar);
        Storage::delete($profile->name_card);
        $profile->delete();
        $agent->delete();
    }

    public function search(Request $request)
    {
        $query = $request->search_agent;
        $agents = User::where([
            ['role', 'agent'],
            ['name', 'LIKE', '%' . $query . '%']
        ])->orWhere([
            ['role', 'agent'],
            ['email', 'LIKE', '%' . $query . '%']
        ])->paginate(10);
        $agents->appends($request->only('search_agent'));
        return view('agent.manage', ['agents' => $agents, 'query' => $query]);
    }
}

app/Http/Controllers/Agent/AgentController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class AgentController extends Controller
{
    public function profile()
    {
//        $listBank = json_decode(File::get('js/bank_indonesia.json'));
//        $profile = User::findOrFail(Auth::id());
//        return view('agent.profile', ['profile' => $profile, 'listBank' => $listBank]);
    }
}

app/Http/Controllers/Agent/HomeController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use App\Order;
use Illuminate\Support\Facades\Auth;
// use App\Service;
use Illuminate\Http\Request;
use App\UserProfile;
use Illuminate\Support\Carbon;

class HomeController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $services = $user->service->sortByDesc('created_at')->take(10);
        $serviceCount = $user->service->count();
        $unfinishedJobCount = $user->agentOrders->where('status', 'process')->count();
        $lastMonthJobCount = $user->agentOrders->where('started_at' ,'>=',Carbon::now()->addDays(-30))->count();
        $orders = Order::where('agent_id', Auth::id())->where(function ($query) {
            $query->where('status', 'process')->orWhere('status', 'complaint');
        })->oldest()->take(10)->get();
        return view('agent.home', [
            'services' => $services,
            'serviceCount' => $serviceCount,
            'unfinishedJobCount'=>$unfinishedJobCount,
            'lastMonthJobCount'=>$lastMonthJobCount,
            'orders' => $orders
        ]);
    }

    public function showAgentProfile($agent_id)
    {
        $profile = UserProfile::where('user_id', $agent_id)->firstOrFail();
        return view('agent.profile')->with('profile', $profile);
    }
}

app/Http/Controllers/Agent/TestimonyController.php
<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Testimony;

class TestimonyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Auth::user()->service;
        $testimonies = Testimony::whereIn('service_id', $services->pluck('id'))->paginate(10);
        return view('testimony.agent.index', [
            'testimonies'=>$testimonies, 
            'services' => $services
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($service_id)
    {
        $testimonies = Testimony::where('service_id', $service_id)->paginate(10);
        return view('testimony.agent.show', [
            'testimonies'=>$testimonies
        ]);
    }
}

resources/views/agent/home.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Agent Dashboard')
@section('page-id', 'agentDashboard')
@section('page-name', 'My Dashboard')
@section('header')
    <div class="row">
        <div class="col-xl-4 col-md-6">
            <div class="card card-stats">
                <div class="card-body">
                    <a href="{{ route('agent.service.index') }}" class="d-block">
                        <div class="row">
                            <div class="col">
                                <h5 class="card-title text-uppercase text-muted mb-0">My Service</h5>
                                <span class="h2 font-weight-bold mb-0">{{$serviceCount}} Post</span>
                            </div>
                            <div class="col-auto">
                                <div class="icon icon-shape bg-gradient-green text-white rounded-circle shadow">
                                    <i class="fas fa-truck-loading"></i>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-xl-4 col-md-6">
            <div class="card card-stats">
                <div class="card-body">
                    <a href="{{ route('agent.list-request.index')}}" class="d-block">
                        <div class="row">
                            <div class="col">
                                <h5 class="card-title text-uppercase text-muted mb-0">Unfinished Job</h5>
                                <span class="h2 font-weight-bold mb-0">{{$unfinishedJobCount}} Project</span>
                            </div>
                            <div class="col-auto">
                                <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                                    <i class="fas fa-spinner"></i>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-xl-4 col-md-12">
            <div class="card card-stats">
                <div class="card-body">
                        <a href="{{ route('agent.list-request.history') }}" class="d-block">
                            <div class="row">
                                <div class="col">
                                    <h5 class="card-title text-uppercase text-muted mb-0">Job Past 30 Days</h5>
                                    <span class="h2 font-weight-bold mb-0">{{$lastMonthJobCount}} Project</span>
                                </div>
                                <div class="col-auto">
                                    <div class="icon icon-shape bg-gradient-indigo text-white rounded-circle shadow">
                                        <i class="fas fa-clipboard-check"></i>
                                    </div>
                                </div>
                            </div>
                        </a>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header border-0 d-flex justify-between align-items-center">
                    <h3 class="mb-0">Customer Request</h3>
                    <a href="{{ route('agent.list-request.index') }}" class="btn btn-sm btn-default">
                        See more
                    </a>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush">
                        <thead class="thead-light">
                        <tr>
                            <th>Order Title</th>
                            <th>Order come in</th>
                            <th>Customer email</th>
                            <th>Status</th>
                            <th colspan="2">Action</th>
                        </tr>
                        </thead>
                        <tbody class="list">
                        @foreach($orders as $order)
                            <tr>
                                <td>
                                    <div class="media align-items-center">
                                        <a href="{{ route('service.show', $order->id) }}"
                                           class="avatar rounded-circle mr-2">
                                            <img alt="Service Cover" height="50px"
                                                 src="{{ Storage::url($order->package->service->image) }}"
                                                 style="width: 50px !important;">
                                        </a>
                                        <div class="media-body">
                                            <span class="name mb-0 text-sm">
                                                {{ Str::words($order->package->service->title, 5) }}
                                            </span>
                                        </div>
                                    </div>
                                </td>
                                <td>{{ $order->created_at->format('d M Y') }}</td>
                                <td>{{ $order->user->email }}</td>
                                <td>{{ $order->status }}</td>
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#"
                                           role="button" data-toggle="dropdown" aria-haspopup="true"
                                           aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            @switch($order->status)
                                                @case('process')
                                                <a class="dropdown-item text-default"
                                                   href="{{ route('agent.list-request.index') .
                                                   '#availableReqest' . ($loop->index + 1) }}">
                                                    See detail
                                                </a>
                                                @break
                                                @case('complaint')
                                                <a class="dropdown-item text-default"
                                                   href="{{ route('agent.list-request.complaint') .
                                                   '#complaintRequest' . ($loop->index + 1) }}">
                                                    See detail
                                                </a>
                                                @break
                                            @endswitch
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card">
                <div class="card-header border-0 bg-default d-flex justify-between align-items-center">
                    <h3 class="mb-0 text-white">My Service Post</h3>
                    <a href="{{ route('agent.service.index') }}" class="btn btn-sm btn-white">See more</a>
                </div>
                <div class="table-responsive">
                    <table class="table align-items-center table-flush table-dark">
                        <thead class="thead-dark">
                        <tr>
                            <th>Service Title</th>
                            <th>Package</th>
                            <th colspan="2">Category</th>
                        </tr>
                        </thead>
                        <tbody class="list">
                        @foreach($services as $service)
                            <tr>
                                <td>
                                    <div class="media align-items-center">
                                        <a href="{{ route('service.show', $service->id) }}"
                                        class="avatar rounded-circle mr-2">
                                            <img alt="Service Cover" height="50px"
                                            src="{{ Storage::url($service->image) }}"
                                            style="width: 50px !important;">
                                        </a>
                                        <div class="media-body">
                                            <span class="name mb-0 text-sm">
                                                {{ Str::words($service->title, 5) }}
                                            </span>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    @foreach($service->package as $package)
                                        {{ $package->title }}
                                    @endforeach
                                </td>
                                <td>{{ $service->serviceCategory->name }}</td>
                                <td class="text-right">
                                    <div class="dropdown">
                                        <a class="btn btn-sm btn-icon-only text-light" href="#"
                                           role="button" data-toggle="dropdown" aria-haspopup="true"
                                           aria-expanded="false">
                                            <i class="fas fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <a class="dropdown-item text-default" target="_blank"
                                               href="{{ route('service.show', $service->id) }}">
                                                See service
                                            </a>
                                            <a href="{{ route('agent.service.edit', $service->id) }}"
                                               class="dropdown-item text-warning">
                                                Edit service
                                            </a>
                                            <form action="{{ route('agent.service.destroy', $service->id) }}">
                                                @csrf @method('DELETE')
                                                <button type="submit" class="dropdown-item text-danger">
                                                    Delete service
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('element')
    <div class="modal fade" id="dashboard-delete-service" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
@endsection