routes/web.php
<?php

use App\Order;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['verify'=>true]);
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('auth.index');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('auth.callback');

Route::get('/', 'HomeController@index')->name('landing-page');
Route::get('services/search', 'HomeController@searchAgentJob')->name('service.search');
Route::get('services', 'HomeController@services')->name('services');
Route::get('service/show/{id}', 'HomeController@showService')->name('service.show');
Route::get('service/show/{id}/filter', 'HomeController@filterService')->name('service.filter-service');

Route::post('order/package/{id}', 'HomeController@makeOrder')->name('order.store')->middleware('auth');
Route::post('order/package/{id}/payment', 'PaymentController@orderPayment')->name('order.payment');
Route::get('order/package/{id}', 'HomeController@redirectOrderPage');
Route::post('payment/notification', 'PaymentController@notification');
Route::get('promo/check', 'HomeController@checkPromoCode')->name('promo.check');
Route::get('contact-us', 'ContactController@index')->name('contact-us.index');
Route::get('faq', 'HomeController@faq')->name('faq.index');
Route::get('faq/search', 'Admin\FaqController@seach')->name('faq.search');
Route::get('testimony', 'HomeController@testimonies')->name('testimony');
Route::get('blog/search', 'BlogController@search')->name('blog.search');
Route::resource('blog', 'BlogController')->only(['index', 'show']);
Route::get('search/agentjob', 'HomeController@searchAgentJob')->name('agentjob.search');
Route::get('blog/categories/{id}', 'BlogCategoryController@show')->name('blog-category.show');
Route::name('message.')->prefix('message')->middleware('exceptAdmin')->group(function () {
    Route::get('/', 'MessageController@index')->name('index');
    Route::get('fetch/{session_id}', 'MessageController@fetch')->name('fetch');
    Route::post('send/{session_id}', 'MessageController@send')->name('send');
});
Route::post('contact-us', 'ContactController@send')->name('contact-us.store');
Route::get('payment/redirect', 'PaymentController@redirect')->name('payment.redirect');

Route::namespace('Admin')->middleware('admin')->prefix('admin')->group(function () {
    Route::get('dashboard', 'AdminController@index')->name('admin.dashboard');
    Route::get('setting', 'AdminController@setting')->name('admin.setting');
    Route::put('token-conversion', 'AdminController@updateToken')->name('admin.convert-token');
    Route::prefix('manage')->name('manage.')->group(function(){
        Route::get('/', 'HomeController@index');
        Route::get('agent/search', 'AgentController@search')->name('agent.search');
        Route::resource('user', 'UserController');
        Route::resource('agent', 'AgentController');
        Route::resource('admin', 'AdminController')->except('index');
        Route::post('faq-category/store', 'FaqController@storeCategory')->name('faq.store-category');
        Route::get('faq-category/destroy/{id}', 'FaqController@destroyCategory')->name('faq.destroy-category');
        Route::resource('faq', 'FaqController')->except(['show']);
        Route::resource('blog', 'BlogController');
        Route::resource('blog-category', 'BlogCategoryController')->only(['store', 'update', 'destroy']);
        Route::resource('service', 'ServiceController')->except(['create']);
        Route::resource('service-category', 'ServiceCategoryController')->except(['create', 'show', 'edit']);
        Route::get('contact-us/search', 'ContactController@search')->name('contact-us.search');
        Route::resource('contact-us', 'ContactController')->except(['create', 'store', 'show']);
        Route::resource('testimony', 'TestimonyController')->only(['index', 'update', 'destroy']);
        Route::resource('promo', 'PromoController')->except(['create', 'show', 'edit']);
        Route::resource('subscription', 'SubscriptionController');
        Route::resource('reason', 'ReasonController')->except(['show']);
        Route::get('package/{id}', 'PackageController@index')->name('package.index');
        Route::resource('package', 'PackageController')->except(['index']);
        Route::get('service-extras/{id}', 'ServiceExtrasController@index')->name('service-extras.index');
        Route::resource('service-extras', 'ServiceExtrasController')->except(['index']);
    });
});

Route::get('download/order/{id}/result/{result_id}', 'DownloadController@downloadResult')->name('order.result.download');

Route::name('user.')->prefix('user')->middleware(['auth', 'verified'])->group(function () {
    Route::resource('subscription', 'SubscriptionController')->only(['index', 'show']);
    Route::post('subscription/show/{id}/payment', 'PaymentController@subscriptionPayment')->name('subscription.payment');
    Route::get('order/{id}/chat', 'MessageController@chat')->name('chat.index');
    Route::get('order/{id}/get-chat', 'MessageController@getChat')->name('chat.get');
    Route::post('order/chat', 'MessageController@sendChat')->name('chat.store');
    Route::prefix('profile')->group(function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::get('edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('edit', 'ProfileController@update')->name('profile.update');
        Route::put('edit/avatar', 'ProfileController@avatarUpdate')->name('profile.avatar.update');
    });
    Route::namespace('User')->group(function() {
        Route::post('order/{id}/review', 'OrderController@sendReview')->name('order.review');
        Route::get('dashboard', 'HomeController@index')->name('dashboard');
        Route::resource('order', 'OrderController');
        Route::get('order/{id}/result/accept/{result_id}', 'OrderController@acceptResult')->name('order.accept');
        Route::get('order/{id}/result/reject/{result_id}', 'OrderController@rejectResult')->name('order.reject');
        Route::resource('job', 'JobController');
        Route::resource('testimony', 'TestimonyController')->only(['index', 'create', 'store']);
        Route::resource('transaction', 'TransactionController');
    });
});

Route::prefix('agent')->name('agent.')->middleware(['agent', 'verified'])->group(function () {
    Route::get('order/{id}/chat', 'MessageController@chat')->name('chat.index');
    Route::post('order/chat', 'MessageController@sendChat')->name('chat.store');
    Route::get('order/{id}/get-chat', 'MessageController@getChat')->name('chat.get');
    Route::prefix('profile')->group(function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::put('edit', 'ProfileController@update')->name('profile.update');
        Route::put('edit/avatar', 'ProfileController@avatarUpdate')->name('profile.avatar.update');
    });
    Route::namespace('Agent')->group(function () {
        Route::get('bid-history', 'OrderController@bidHistory')->name('bid-history');
        Route::redirect('/', 'dashboard');
        Route::get('dashboard', 'HomeController@index')->name('dashboard');
        Route::get('testimony', 'TestimonyController@index')->name('testimony.index');
        Route::get('testimony/{service_id}', 'TestimonyController@show')->name('testimony.show');
        Route::get('service/see-extras/{id}', 'ServiceController@seeExtras')->name('service.extras');
        Route::resource('service', 'ServiceController');
        Route::get('service/manage-package/{id}', 'ServiceController@managePackage')->name('service.package');
        Route::get('list-request/complaint', 'OrderController@complaint')->name('list-request.complaint');
        Route::get('list-request/history', 'OrderController@history')->name('list-request.history');
        Route::get('list-request/incoming', 'OrderController@incoming')->name('list-request.incoming');
        Route::put('list-request/approval/{id}', 'OrderController@approval')->name('list-request.approval');
        Route::put('list-request/progress/{id}', 'OrderController@progressUpdate')->name('list-request.progress');
        Route::delete('list-request/delete/{id}', 'OrderController@destroy');
        Route::post('list-request/send-review/{id}', 'OrderController@sendReview')->name('list-request.send-review');
        Route::post('list-request/send-result/{id}', 'OrderController@sendResult')->name('list-request.send-result');
        Route::post('list-request/send-revision/{id}', 'OrderController@sendRevision')->name('list-request.send-revision');
        Route::get('list-request/search', 'OrderController@search')->name('list-request.search');
        Route::resource('list-request', 'OrderController');
        Route::resource('portfolio', 'PortfolioController');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Carbon;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password', 'role', 'is_subscribe', 'subscribe_to', 'username', 'email_verified_at',
        'subscribe_at', 'subscribe_token', 'subscribe_duration', 'provider_id', 'provider'
    ];
    protected $hidden = ['password', 'remember_token'];
    protected $casts = ['email_verified_at' => 'datetime', 'subscribe_at'=>'datetime'];

    public function service()
    {
        return $this->hasMany('App\Service', 'agent_id');
    }

    public function profile()
    {
        return $this->hasOne('App\UserProfile', 'user_id', 'id');
    }

    public function chatSession()
    {
        if ($this->role != 'admin') {
            return $this->hasMany('App\ChatSession', $this->role.'_id')->where('blocked', 0);
        }
    }

    public function userOrders()
    {
        return $this->hasMany('App\Order', 'user_id');
    }

    public function agentOrders()
    {
        return $this->hasMany('App\Order', 'agent_id');
    }

    public function subscription()
    {
        return $this->hasMany('App\SubscribeData')->where('expired_at', '>', Carbon::now())->orderBy('expired_at', 'ASC');
    }

    public function subscriptionOrder()
    {
        return $this->hasMany('App\SubscriptionOrder');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $users = User::where('role', 'user')->get();
        return view('user.manage', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'password' => 'required|min:8',
        ]);
        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'role' => 'user',
        ]);
        return redirect()->back()->with('success', 'User Account Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::where('role', 'user')->findOrFail($id);
        return view('user.show', ['user', $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::where('role', 'user')->findOrFail($id);
        return view('user.edit', ['user', $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'user_email' => 'required|email',
            'user_name' => 'required',
            'user_phone' => 'required',
            'user_bank' => 'required',
            'user_account' => 'required|number',
            'user_address' => 'required'
        ]);
        $user = User::where('role', 'user')->findOrFail($id);
        $user->email = $request->user_email;
        $user->name = $request->user_name;
        $user->profile->handphone = $request->user_phone;
        $user->profile->bank = $request->user_bank;
        $user->profile->account_number = $request->user_account;
        $user->profile->address = $request->user_address;
        $user->profile->save();
        $user->save();
        return redirect()->back()->with('success', 'User Account Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::where('role', 'user')->findOrFail($id);
        $profile = $user->profile;
        Storage::delete($profile->avatar);
        Storage::delete($profile->name_card);
        $profile->delete();
        $user->delete();
    }
}

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
    }
    public function index()
    {
        return view('user.home');
    }
}

app/Http/Controllers/User/JobController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

class JobController extends Controller
{

    public function index()
    {
        $listBank = json_decode(File::get('js/bank_indonesia.json'));
        $orders = Order::where('user_id', Auth::id())->get();
        return view('job.manage', ['listBank' => $listBank, 'orders' => $orders]);
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/TestimonyController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Testimony;
use App\Service;

class TestimonyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $testimonies = Testimony::where('user_id', User::id())->paginate(10);
        return view('testimony.user.index', ['testimonies' => $testimonies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Service $service)
    {
        return view('testimony.user.create', ['service'=>$service]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Service $service
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Service $service)
    {
        $request->validate([
            'content' => 'required',
            'rating' => 'required|digits_between:0,10',
        ]);
        $testimony = new Testimony;
        $testimony->content = $request->content;
        $testimony->rating = $request->rating;
        $testimony->service_id = $service->id;
        $testimony->user_id = Auth::id();
        $testimony->save();
        return redirect()->back()->with('success', 'Testimony Submitted Successfully');
    }
}

resources/views/user/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">User Home</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in. <a href="{{ route('landing-page') }}">Let's order something!</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/order.blade.php
@extends('layouts.customer-master')
@section('page-title', 'Order Management')
@section('page-id', 'userOrder')
@section('css') <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> @endsection
@section('header')
    <header>
        @include('partials.nav')
    </header>
@endsection
@section('script')
    <script data-client-key="{{ env('MIDTRANS_CLIENT_KEY') }}" src="https://app.midtrans.com/snap/snap.js"></script>
    <script>
        let filter = $('#order-filter').val();
        $('#order-filter').change(function(){
            if($(this).val() !== filter){
                $('#form-filter-order').submit();
            }
        });
    </script>
@endsection
@section('content')
    @if (session('success'))
        <div class="alert alert--success">
            {{ session('success') }}
        </div>
    @endif
    @if (session('error'))
        <div class="alert alert--error">
            {{ session('error') }}
        </div>
    @endif
    <div class="container">
        <div class="row justify-content-between align-items-start">
            @include('user.profile')
            <section class="profile-main">
                @include('partials.profile-nav')
                <form id="form-filter-order" action="" class="profile-main__filter">
                    <label for="order-filter"><h1>Your order</h1></label>
                    <select name="filter" id="order-filter" class="profile-main__orderBy wide mt-3 mt-lg-0">
                        <option value="all" {{(!session('filter') or session('filter') == 'all') ? 'selected=selected' : ''}}>
                            All order
                        </option>
                        <option value="completed" {{(session('filter') == 'completed') ? 'selected=selected' : ''}}>
                            Completed
                        </option>
                        <option value="process" {{(session('filter') == 'process') ? 'selected=selected' : ''}}>
                            Active
                        </option>
                        <option value="canceled" {{(session('filter') == 'canceled') ? 'selected=selected' : ''}}>
                            Canceled
                        </option>
                    </select>
                </form>
                <div class="profile-main__content">
                    @forelse($orders as $order)
                        <article class="profile-main-item">
                            <img src="{{ Storage::url($order->package->image) }}" class="profile-main__order-img"
                                 alt="order image {{ $order->id }}" data-id="{{ $order->id }}">
                            <div class="profile-main__order-detail ml-xl-5">
                                <div class="mb-3">
                                    What you order
                                    <span class="profile-main__title">
                                        {{ Str::limit($order->package->service->title, 30) ?? 'service deleted by admin'}}
                                    </span>
                                </div>
                                <div class="mb-3">
                                    Start on:
                                    <time class="profile-main__time">
                                        {{ $order->started_at ?? 'not start yet' }}
                                    </time>
                                </div>
                                <div class="mb-3">
                                    Finish on:
                                    <time class="profile-main__time">{{ $order->deadline ?? '-' }}</time>
                                </div>
                                @if ($order->status == 'process')
                                    <div class="mb-3">
                                        Progress
                                        <progress max="100" value="{{ $order->progress }}">{{ $order->progress }}</progress>
                                    </div>
                                @elseif ($order->status != 'process')
                                    <div class="mb-3">
                                        Status
                                        @if ($order->status == 'complaint' or $order->status == 'canceled')
                                            <p class="text-danger font-bold">{{ $order->status }}</p>
                                        @elseif($order->status == 'unpaid')
                                            <p class="text-warning font-bold">{{ $order->status }}</p>
                                        @elseif($order->status == 'check_revision' or $order->status == 'check_result')
                                        <p class="text-success font-bold">{{ $order->status }}</p>
                                        @elseif ($order->waiting == 'waiting')
                                            <p class="text-gray font-bold">{{ $order->status }}</p>
                                        @else
                                            <p class="text-success font-bold">{{ $order->status }}</p>
                                        @endif
                                    </div>
                                    @if (!empty($order->invoice))
                                        <div class="mb-3 d-flex flex-column flex-md-row">
                                            <a href="javascript:void(0);" class="btn btn-pay"
                                            data-payment-token="{{$order->invoice->payment_token ?? ''}}">
                                                Pay now
                                            </a>
                                        </div>
                                    @endif
                                @endif
                                @if (!empty($order->result))
                                    <div class="mb-3 d-flex flex-column flex-md-row">
                                        <a class="btn text-warning" href="{{ route('order.result.download',
                                        ['id'=>$order->id, 'result_id'=>$order->result->id]) }}">
                                            Download Result
                                        </a>
                                    </div>
                                    @if ($order->status == 'check_result')
                                        <div class="mb-3 d-flex flex-column flex-md-row">
                                            <a class="btn text-success" href="{{ route('user.order.accept',
                                            ['id'=>$order->id, 'result_id'=>$order->result->id]) }}">
                                                Accept Result
                                            </a>
                                            <a class="btn text-danger" href="{{ route('user.order.reject',
                                            ['id'=>$order->id, 'result_id'=>$order->result->id]) }}">
                                                Reject Result ({{ $order->max_revision - $order->revision->count() }}
                                                revision left)
                                            </a>
                                        </div>
                                    @endif
                                @endif
                                @if ($order->revision->count() > 0)
                                    @foreach ($order->revision as $revision)
                                        <div class="mb-3 d-flex flex-column flex-md-row">
                                            <a class="btn text-warning" href="{{ route('order.result.download',
                                                   ['id'=>$order->id, 'result_id'=>$revision->id]) }}">
                                                Download Revision {{ $loop->iteration }}
                                            </a>
                                        </div>
                                    @endforeach
                                    @if ($order->status == 'check_revision')
                                        <div class="mb-3 d-flex flex-column flex-md-row">
                                            <a class="btn text-success" href="{{ route('user.order.accept',
                                            ['id'=>$order->id, 'result_id'=>$order->revision->last()->id]) }}">
                                                Accept Result
                                            </a>
                                            <a class="btn text-danger" href="{{ route('user.order.reject',
                                            ['id'=>$order->id, 'result_id'=>$order->revision->last()->id]) }}">
                                                Reject Result
                                                ({{ $order->max_revision - $order->revision->count() }} revision left)
                                            </a>
                                        </div>
                                    @endif
                                @endif
                                <a href="{{ route('user.chat.index', $order->id) }}" class="profile-main__btn-chat">
                                    Chat agent
                                </a>
                                @if (!$order->is_reviewed AND $order->status === 'finished' and $order->is_reviewed == false)
                                    <a href="javascript:void(0);" class="btn-success btn-modal"
                                       data-target="#modal-review{{ $loop->index + 1 }}">
                                        Review
                                    </a>
                                @elseif($order->is_reviewed == true)
                                    <button type="button" class="btn-success" disabled>
                                        Already Reviewed
                                    </button>
                                @endif
                            </div>
                        </article>
                    @empty
                        <img src="{{ asset('img/empty-state.svg') }}" alt="No request" class="mx-auto d-block my-5">
                        <h1 class="text-center display-4 text-muted">You have no order</h1>
                    @endforelse
                    {{ $orders->links() }}
                </div>
            </section>
        </div>
    </div>
@endsection
@push('element')
    @isset($orders)
        @foreach($orders as $order)
            @include('partials.review-job')
        @endforeach
    @endisset
@endpush

resources/views/user/post-job.blade.php
@extends('layouts.customer-master')
@section('page-title', 'Post a Job')
@section('page-id', 'postJob')
@section('header')
    @include('partials.nav')
@endsection
@section('content')
    <div class="container">
        
    </div>
@endsection