routes/web.php
<?php

use App\Order;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['verify'=>true]);
Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider')->name('auth.index');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->name('auth.callback');

Route::get('/', 'HomeController@index')->name('landing-page');
Route::get('services/search', 'HomeController@searchAgentJob')->name('service.search');
Route::get('services', 'HomeController@services')->name('services');
Route::get('service/show/{id}', 'HomeController@showService')->name('service.show');
Route::get('service/show/{id}/filter', 'HomeController@filterService')->name('service.filter-service');

Route::post('order/package/{id}', 'HomeController@makeOrder')->name('order.store')->middleware('auth');
Route::post('order/package/{id}/payment', 'PaymentController@orderPayment')->name('order.payment');
Route::get('order/package/{id}', 'HomeController@redirectOrderPage');
Route::post('payment/notification', 'PaymentController@notification');
Route::get('promo/check', 'HomeController@checkPromoCode')->name('promo.check');
Route::get('contact-us', 'ContactController@index')->name('contact-us.index');
Route::get('faq', 'HomeController@faq')->name('faq.index');
Route::get('faq/search', 'Admin\FaqController@seach')->name('faq.search');
Route::get('testimony', 'HomeController@testimonies')->name('testimony');
Route::get('blog/search', 'BlogController@search')->name('blog.search');
Route::resource('blog', 'BlogController')->only(['index', 'show']);
Route::get('search/agentjob', 'HomeController@searchAgentJob')->name('agentjob.search');
Route::get('blog/categories/{id}', 'BlogCategoryController@show')->name('blog-category.show');
Route::name('message.')->prefix('message')->middleware('exceptAdmin')->group(function () {
    Route::get('/', 'MessageController@index')->name('index');
    Route::get('fetch/{session_id}', 'MessageController@fetch')->name('fetch');
    Route::post('send/{session_id}', 'MessageController@send')->name('send');
});
Route::post('contact-us', 'ContactController@send')->name('contact-us.store');
Route::get('payment/redirect', 'PaymentController@redirect')->name('payment.redirect');

Route::namespace('Admin')->middleware('admin')->prefix('admin')->group(function () {
    Route::get('dashboard', 'AdminController@index')->name('admin.dashboard');
    Route::get('setting', 'AdminController@setting')->name('admin.setting');
    Route::put('token-conversion', 'AdminController@updateToken')->name('admin.convert-token');
    Route::prefix('manage')->name('manage.')->group(function(){
        Route::get('/', 'HomeController@index');
        Route::get('agent/search', 'AgentController@search')->name('agent.search');
        Route::resource('user', 'UserController');
        Route::resource('agent', 'AgentController');
        Route::resource('admin', 'AdminController')->except('index');
        Route::post('faq-category/store', 'FaqController@storeCategory')->name('faq.store-category');
        Route::get('faq-category/destroy/{id}', 'FaqController@destroyCategory')->name('faq.destroy-category');
        Route::resource('faq', 'FaqController')->except(['show']);
        Route::resource('blog', 'BlogController');
        Route::resource('blog-category', 'BlogCategoryController')->only(['store', 'update', 'destroy']);
        Route::resource('service', 'ServiceController')->except(['create']);
        Route::resource('service-category', 'ServiceCategoryController')->except(['create', 'show', 'edit']);
        Route::get('contact-us/search', 'ContactController@search')->name('contact-us.search');
        Route::resource('contact-us', 'ContactController')->except(['create', 'store', 'show']);
        Route::resource('testimony', 'TestimonyController')->only(['index', 'update', 'destroy']);
        Route::resource('promo', 'PromoController')->except(['create', 'show', 'edit']);
        Route::resource('subscription', 'SubscriptionController');
        Route::resource('reason', 'ReasonController')->except(['show']);
        Route::get('package/{id}', 'PackageController@index')->name('package.index');
        Route::resource('package', 'PackageController')->except(['index']);
        Route::get('service-extras/{id}', 'ServiceExtrasController@index')->name('service-extras.index');
        Route::resource('service-extras', 'ServiceExtrasController')->except(['index']);
    });
});

Route::get('download/order/{id}/result/{result_id}', 'DownloadController@downloadResult')->name('order.result.download');

Route::name('user.')->prefix('user')->middleware(['auth', 'verified'])->group(function () {
    Route::resource('subscription', 'SubscriptionController')->only(['index', 'show']);
    Route::post('subscription/show/{id}/payment', 'PaymentController@subscriptionPayment')->name('subscription.payment');
    Route::get('order/{id}/chat', 'MessageController@chat')->name('chat.index');
    Route::get('order/{id}/get-chat', 'MessageController@getChat')->name('chat.get');
    Route::post('order/chat', 'MessageController@sendChat')->name('chat.store');
    Route::prefix('profile')->group(function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::get('edit', 'ProfileController@edit')->name('profile.edit');
        Route::put('edit', 'ProfileController@update')->name('profile.update');
        Route::put('edit/avatar', 'ProfileController@avatarUpdate')->name('profile.avatar.update');
    });
    Route::namespace('User')->group(function() {
        Route::post('order/{id}/review', 'OrderController@sendReview')->name('order.review');
        Route::get('dashboard', 'HomeController@index')->name('dashboard');
        Route::resource('order', 'OrderController');
        Route::get('order/{id}/result/accept/{result_id}', 'OrderController@acceptResult')->name('order.accept');
        Route::get('order/{id}/result/reject/{result_id}', 'OrderController@rejectResult')->name('order.reject');
        Route::resource('job', 'JobController');
        Route::resource('testimony', 'TestimonyController')->only(['index', 'create', 'store']);
        Route::resource('transaction', 'TransactionController');
    });
});

Route::prefix('agent')->name('agent.')->middleware(['agent', 'verified'])->group(function () {
    Route::get('order/{id}/chat', 'MessageController@chat')->name('chat.index');
    Route::post('order/chat', 'MessageController@sendChat')->name('chat.store');
    Route::get('order/{id}/get-chat', 'MessageController@getChat')->name('chat.get');
    Route::prefix('profile')->group(function () {
        Route::get('/', 'ProfileController@index')->name('profile.index');
        Route::put('edit', 'ProfileController@update')->name('profile.update');
        Route::put('edit/avatar', 'ProfileController@avatarUpdate')->name('profile.avatar.update');
    });
    Route::namespace('Agent')->group(function () {
        Route::get('bid-history', 'OrderController@bidHistory')->name('bid-history');
        Route::redirect('/', 'dashboard');
        Route::get('dashboard', 'HomeController@index')->name('dashboard');
        Route::get('testimony', 'TestimonyController@index')->name('testimony.index');
        Route::get('testimony/{service_id}', 'TestimonyController@show')->name('testimony.show');
        Route::get('service/see-extras/{id}', 'ServiceController@seeExtras')->name('service.extras');
        Route::resource('service', 'ServiceController');
        Route::get('service/manage-package/{id}', 'ServiceController@managePackage')->name('service.package');
        Route::get('list-request/complaint', 'OrderController@complaint')->name('list-request.complaint');
        Route::get('list-request/history', 'OrderController@history')->name('list-request.history');
        Route::get('list-request/incoming', 'OrderController@incoming')->name('list-request.incoming');
        Route::put('list-request/approval/{id}', 'OrderController@approval')->name('list-request.approval');
        Route::put('list-request/progress/{id}', 'OrderController@progressUpdate')->name('list-request.progress');
        Route::delete('list-request/delete/{id}', 'OrderController@destroy');
        Route::post('list-request/send-review/{id}', 'OrderController@sendReview')->name('list-request.send-review');
        Route::post('list-request/send-result/{id}', 'OrderController@sendResult')->name('list-request.send-result');
        Route::post('list-request/send-revision/{id}', 'OrderController@sendRevision')->name('list-request.send-revision');
        Route::get('list-request/search', 'OrderController@search')->name('list-request.search');
        Route::resource('list-request', 'OrderController');
        Route::resource('portfolio', 'PortfolioController');
    });
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $table = 'blog';
    protected $with = ['category'];
    protected $fillable = ['title', 'header_image', 'contents', 'category_id', 'hits', 'is_main'];

    public function category()
    {
        return $this->belongsTo('App\BlogCategory', 'category_id');
    }
}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Blog;
use App\BlogCategory;

class BlogController extends Controller
{

    public function index()
    {
        $blogs = Blog::with('category')->latest()->paginate(10);
        $number = $blogs->firstItem();
        $blogCategories = BlogCategory::all();
        return view('blog.manage-article', [
            'blogs' => $blogs,
            'number' => $number,
            'blogCategories' => $blogCategories
        ]);
    }

    public function create()
    {
        $mainArticles = Blog::where('is_main', true)->count();
        $categories = BlogCategory::all();
        return view('blog.create-article', ['categories' => $categories, 'mainArticles' => $mainArticles]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'header_image' => 'required|image',
            'category_id' => 'required',
            'contents' => 'required',
        ]);
        $img_path = $request->file('header_image')->store('public/files');
        $createBlog = new Blog;
        $createBlog->header_image = $img_path;
        $createBlog->title = $request->title;
        $createBlog->category_id = $request->category_id;
        $createBlog->contents = $request->contents;
        if (Blog::all()->count() <= 6) {
            if ($request->is_main == "true") {
                $createBlog->is_main = true;
            } else {
                $createBlog->is_main = false;
            }
        }else {
            $createBlog->is_main = false;
        }
        $createBlog->save();
        return redirect()->route('manage.blog.index')->with('success', 'Blog Created Successfully');
    }

    public function show($id)
    {
        $blog = Blog::with('category')->findOrFail($id);
        $popular = Blog::orderBy('hits', 'desc')->take(3)->get();
        $related_blogs = Blog::with('category')->inRandomOrder()->take(3)->get()->except($id);
        return view('blog.single', [
            'blog' => $blog,
            'relates' => $related_blogs,
            'popular' => $popular
        ]);
    }

    public function edit($id)
    {
        $article = Blog::findOrFail($id);
        $mainArticles = Blog::where('is_main', true)->count();
        $categories = BlogCategory::all();
        return view('blog.edit', [
            'article'=> $article,
            'categories' => $categories,
            'mainArticles' => $mainArticles
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
            'header_image' => 'nullable|image',
            'category_id' => 'required',
            'contents' => 'required',
        ]);
        $blog = Blog::findOrFail($id);
        $blog->title = $request->title;
        $blog->contents = $request->contents;
        $blog->category_id = $request->category_id;
        if ($request->hasFile('header_image')) {
            Storage::delete($blog->header_image);
            $blog->header_image = $request->file('header_image')->store('public/files');
        }
        $blog->is_main = intval($request->is_main);
        $blog->save();
        return redirect()->route('manage.blog.index')->with('success', 'Blog update succefully');
    }

    public function destroy($id)
    {
        $blog = Blog::findOrFail($id);
        Storage::delete($blog->header_image);
        $blog->delete();
        return redirect()->route('manage.blog.index')->with('success', 'Blog delete succefully');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Blog;
use App\BlogCategory;

class BlogController extends Controller
{
    public function index()
    {
        $allBlog = Blog::all();
        $blogs = Blog::latest()->paginate(5);
        $populars = Blog::orderBy('hits', 'DESC')->take(3)->get();
        $mainArticle = Blog::where('is_main', true)->orderBy('updated_at', 'DESC')->take(6)->get();
        $categories = BlogCategory::all();
        return view('blog.index', [
            'blogs'=> $blogs,
            'populars' => $populars,
            'categories' => $categories,
            'mainArticle' => $mainArticle,
            'allBlog' => $allBlog
        ]);
    }

    public function show($id)
    {
        $blog = Blog::with('category')->findOrFail($id);
        $blog->hits = (!$blog->hits) ? 1 : $blog->hits++;
        $blog->update();
        $popular = Blog::orderBy('hits', 'desc')->take(3)->get();
        $blog_categories = BlogCategory::all();
        $related_blogs = Blog::with('category')->inRandomOrder()->take(3)->get()->except($id);
        return view('blog.single', [
            'blog' => $blog,
            'relates' => $related_blogs,
            'popular' => $popular,
            'categories' => $blog_categories
        ]);
    }

    public function search(Request $request)
    {
        $blogs = Blog::with('category')
                ->where('title', 'LIKE', '%' . $request->search_article . '%')
                ->orWhere('contents', 'LIKE', '%' . $request->search_article . '%')
                ->paginate(10);
        $populars = Blog::orderBy('hits', 'DESC')->take(3)->get();
        $mainArticle = Blog::where('is_main', true)->orderBy('updated_at', 'DESC')->take(6)->get();
        $categories = BlogCategory::all();
        $blogs->appends($request->only('search_article'));
        $query = $request->search_article;
        $allBlog = Blog::all();
        return view('blog.index', [
            'blogs' => $blogs,
            'populars' => $populars,
            'categories' => $categories,
            'mainArticle' => $mainArticle,
            'query' => $query,
            'allBlog' => $allBlog
        ]);
    }

}

resources/views/blog/create-article.blade.php
@extends('layouts.blog-master')
@section('page-title', 'Create new article')
@section('page-id', 'blogCreate')
@section('content')
    @if ($errors->any())
        <div class="alert alert--danger">
            @foreach($errors->all() as $error)
                {{ $error }}
            @endforeach
        </div>
    @elseif(session('success'))
        <div class="alert alert--success">
            {{ session('success') }}
        </div>
    @endif
  <div class="container py-4">
      <form action="{{ route('manage.blog.store') }}" method="post" enctype="multipart/form-data">
          @include('blog.form')
          <a href="" class="btn text-warning"><i class='bx bx-left-arrow-alt' ></i> Back</a>
          <button type="submit" class="btn btn-success float-right">Add new article</button>
      </form>
  </div>
@endsection
@section('element')
  <div class="modal fade" id="blog-add-category">
      <div class="modal__content">
          <div class="modal__header">
              <h5 class="modal__title">Add new category</h5>
              <a href="javascript:void(0);" class="btn-close-modal">
                  <i class='bx bx-x'></i>
              </a>
          </div>
          <div class="modal__body pt-4">
              <form class="" id="form-add-category" action="{{ route('manage.blog-category.store') }}" method="post">
                  @csrf
                  <div class="col-12 px-0">
                      <label for="add-category" class="d-none">Add category here</label>
                      <input type="text" placeholder="Ex: promos" id="add-category" class="input-custom" name="name" required>
                  </div>
              </form>
          </div>
          <div class="modal__footer">
              <button type="submit" form="form-add-category" class="btn btn-success d-block col-12">
                  Submit
              </button>
          </div>
      </div>
  </div>
@endsection
@push('script')
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
@endpush

resources/views/blog/edit.blade.php
@extends('layouts.blog-master')
@section('page-title', 'Edit article')
@section('page-id', 'blogEdit')
@section('css')
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
@endsection
@section('content')
  <div class="container py-4">
  <form action="{{ route('manage.blog.update', $article->id) }}" method="post" enctype="multipart/form-data">
      @method('PUT') @include('blog.form')
      <button type="submit" class="btn btn-success btn-block">Update article</button>
    </form>
  </div>
@endsection

resources/views/blog/manage-article.blade.php
@extends('layouts.admin-master')
@section('page-title', 'Blog Management')
@section('page-name', 'Blog Management')
@section('content')
    @if (session('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span class="alert-text">{{ session('success') }}</span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @elseif(session('update_category'))
        <div class="alert alert-success" role="alert">
            {{ session('update_category') }}
        </div>
    @elseif(session('creata_category'))
        <div class="alert alert-success" role="alert">
            {{ session('creata_category') }}
        </div>
    @elseif($errors->any())
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <p class="alert-text mb-0">
                @foreach ($errors->all() as $error)
                    <span class="d-block">{{ $error }}</span>
                @endforeach
            </p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    <div class="row">
        <div class="col-12 px-0">
            <div class="nav-wrapper">
                <ul class="nav nav-pills nav-fill flex-column flex-md-row" id="tabs-icons-text" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link mb-sm-3 mb-md-0 active" id="tab-article-text-1-tab" data-toggle="tab"
                           href="#tab-article" role="tab" aria-controls="tab-article-text-1" aria-selected="true">
                            <i class="ni ni-cloud-upload-96 mr-2"></i> Articles
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mb-sm-3 mb-md-0" id="tab-category-text-2-tab" data-toggle="tab"
                           href="#tab-category" role="tab" aria-controls="tab-category-text-2" aria-selected="false">
                            <i class="ni ni-bell-55 mr-2"></i> Categories
                        </a>
                    </li>
                </ul>
            </div>
            <div class="tab-content py-4">
                <div class="tab-pane fade show active" id="tab-article" role="tabpanel"
                     aria-labelledby="tab-article-text-1-tab">
                    <div class="card">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h3 class="mb-0">All Article</h3>
                                </div>
                                <div class="col text-right">
                                    <a href="{{ route('manage.blog.create') }}" class="btn btn-sm btn-primary">
                                        create new article
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table align-items-center table-flush">
                                <thead class="thead-light">
                                <tr>
                                    <th>No.</th>
                                    <th>Category</th>
                                    <th>Title</th>
                                    <th class="text-center">Show article</th>
                                    <th>Show on homepage</th>
                                    <th>Created At</th>
                                    <th class="text-center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($blogs as $article)
                                    <tr>
                                        <td>{{ $number++ }}</td>
                                        <td>{{ $article->category->name }}</td>
                                        <td>{{ Str::words($article->title, 6) }}</td>
                                        <td class="text-center">
                                            <a href="{{ route('blog.show', $article->id) }}"
                                            class="btn btn-primary btn-sm" target="_blank">
                                                See article
                                            </a>
                                        </td>
                                        <td>
                                            @if ($article->is_main == 1)
                                                True
                                            @else
                                                False
                                            @endif
                                        </td>
                                        <td>{{ $article->created_at->format('d M Y') }}</td>
                                        <td class="text-center">
                                            <a class="btn btn-warning"
                                            href="{{ route('manage.blog.edit', $article->id) }}">
                                                Edit
                                            </a>
                                            <button type="button" class="btn btn-danger show-modal" data-toggle="modal"
                                                    data-article-title="{{ Str::slug($article->title, '-') }}"
                                                    data-target="#delete-article" data-article-id="{{ $article->id }}">
                                                Delete
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="col-12">{{ $blogs->links() }}</div>
                    </div>
                </div>
                <div class="tab-pane fade" id="tab-category" role="tabpanel" aria-labelledby="tab-category-text-2-tab">
                    <div class="card bg-default" style="overflow: hidden">
                        <div class="card-header bg-transparent border-0">
                            <div class="row mx-0 justify-content-between align-items-center">
                                <h3 class="text-white mb-0">All Category</h3>
                                <button type="button" class="btn btn-success btn-sm" data-toggle="modal"
                                        data-target="#add-category-article">
                                    Create new category
                                </button>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table align-items-center table-dark table-flush">
                                <thead class="thead-dark">
                                <tr>
                                    <th>No</th>
                                    <th>Category Name</th>
                                    <th class="text-center">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach ($blogCategories as $category)
                                        <tr>
                                            <td>{{ $loop->index + 1 }}</td>
                                            <td>{{ $category->name  }}</td>
                                            <td class="text-center">
                                                <button type="button" class="btn btn-warning"
                                                        data-toggle="modal" data-target="#edit-category-article"
                                                        data-category-name="{{ Str::slug($category->name, '-') }}"
                                                        data-category-id="{{ $category->id }}">
                                                    Edit
                                                </button>
                                                <button type="button" class="btn btn-danger"
                                                        data-toggle="modal" data-target="#delete-category-article"
                                                        data-category-name="{{ Str::slug($category->name, '-') }}"
                                                        data-category-id="{{ $category->id }}">
                                                    Delete
                                                </button>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('element')
    @include('blog.manipulate')
@endsection

resources/views/blog/single.blade.php
@extends('layouts.blog-master')
@section('page-title')
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, non.
@endsection
@section('page-id', 'blogSingle')
@section('content')
<div class="container">
    <div class="row justify-content-between py-5" id="single-article">
      <section class="col-12 col-md-8">
        <figure class="single-article__top">
          <img src="{{ Storage::url($blog->header_image) }}" alt="{{ $blog->title }}">
          <figcaption class="single-article__info">
            <h1 class="single-article__title">{{ $blog->title }}</h1>
            <a href="{{ route('blog-category.show', $blog->category_id) }}" class="single-article__category">
                {{ $blog->category->name }}
            </a>
            <time class="single-article__time">{{ $blog->updated_at->format('d M, Y') }}</time>
          </figcaption>
        </figure>
        <div class="singe-article__bottom">{!! $blog->contents !!}</div>
      </section>
      <aside class="col-12 col-md-4 col-lg-3 mt-4 mt-md-0">
        <div class="article-popular">
          <h3 class="article-popular__heading">
            <span>Most Popular</span>
          </h3>
          @foreach ($popular as $article)
          <article class="mb-5">
            <div class="article__detail pl-0">
              <p class="article__title article__title--popular">
                <a href="{{ route('blog.show', $article->id) }}">{{ $article->title }}</a>
              </p>
              <span class="article-popular__category">{{ $article->category->name }}</span>
              <time class="article-popular__time">{{ $article->updated_at->format('d M, Y') }}</time>
            </div>
            <img src="{{ asset('img/article2.jpg') }}" class="article__img article__img--popular" alt="Popular blog">
          </article>
          @endforeach
        </div>
        <div class="article-popular">
          <h3 class="article-popular__heading">
            <span>Related stories</span>
          </h3>
          @foreach ($relates as $related)
          <article class="mb-5">
            <div class="article__detail pl-0">
              <p class="article__title article__title--popular">
                <a href="{{ route('blog.show', $related->id) }}">{{ $related->title }}</a>
              </p>
              <span class="article-popular__category">{{ $related->category->name }}</span>
              <time class="article-popular__time">{{ $related->updated_at->format('d M, Y') }}</time>
            </div>
            <img src="{{ asset('img/article2.jpg') }}" class="article__img article__img--popular">
          </article>
          @endforeach
        </div>
      </aside>
    </div>
  </div>
@endsection